document.querySelector('#submitQuiz').addEventListener('click',()=>{if(document.querySelectorAll('.answer-option.selected').length<questions.length)return;questions.forEach((question,index)=>{const questionElement=document.querySelector(`.quiz-question[data-index="${index}"]`);const selected=questionElement.querySelector('.answer-option.selected');const correct=questionElement.querySelector(`.answer-option[data-option="${question.answer}"]`);questionElement.classList.remove('is-wrong','is-correct');questionElement.querySelectorAll('.answer-option').forEach(option=>option.classList.remove('correct-answer','wrong-answer'));correct.classList.add('correct-answer');if(Number(selected.dataset.option)===question.answer){questionElement.classList.add('is-correct');}else{questionElement.classList.add('is-wrong');selected.classList.add('wrong-answer');}});});
const cards=[
  ['Git','The distributed version control system that tracks changes locally.','Git is the tool. GitHub is the platform around it.'],
  ['Repository','A project folder plus its complete version history.','A repository can live locally and have a hosted remote on GitHub.'],
  ['Commit','A saved snapshot of changes with a message.','Good commits are focused, understandable units of work.'],
  ['Branch','An independent line of development.','Branches let you experiment or work safely without changing the default branch.'],
  ['Remote','A hosted copy of a repository.','GitHub commonly acts as the remote that teammates share.'],
  ['GitHub flow','Branch, change, open a pull request, review, then merge.','It gives teams a lightweight, repeatable path from idea to integrated change.']
];
const questions=[
  {topic:'Git concepts',question:'What is Git primarily used for?',options:['Hosting a website','Tracking changes to files and their history','Managing a team calendar','Writing markdown only'],answer:1,why:'Review the difference between Git as a version control tool and GitHub as a platform.'},
  {topic:'Git concepts',question:'Which description best matches a commit?',options:['A hosted copy of a repository','A discussion thread','A saved snapshot of changes','A new GitHub account'],answer:2,why:'Revisit commits as meaningful, saved snapshots in project history.'},
  {topic:'GitHub basics',question:'What does GitHub add around Git repositories?',options:['Collaboration, hosting, and project tools','A replacement for every code editor','Only local file storage','A programming language'],answer:0,why:'Review the Git versus GitHub comparison and the platform capabilities.'},
  {topic:'GitHub flow',question:'Why create a branch before making a change?',options:['To delete the repository history','To create a safe, independent line of work','To turn Git into GitHub','To automatically merge code'],answer:1,why:'Revisit how branches isolate work before it is reviewed and merged.'},
  {topic:'GitHub flow',question:'What is the purpose of a pull request in the GitHub flow?',options:['To review and discuss a proposed change','To download Git','To rename a repository','To create a local commit'],answer:0,why:'Review the flow sequence: branch, change, pull request, review, merge.'},
  {topic:'Repository vocabulary',question:'What is a remote?',options:['An editor shortcut','A hosted copy of a repository','A type of commit message','A branch that cannot be merged'],answer:1,why:'Revisit repository vocabulary, especially local copies and hosted remotes.'}
];

document.querySelector('#flashcardGrid').innerHTML=cards.map((card,index)=>`<button class="flashcard" type="button" aria-label="Flip flashcard ${index+1}"><span class="flashcard-inner"><span class="flashcard-face flashcard-front"><small>0${index+1} / FLASHCARD</small><strong>${card[0]}</strong><span class="flip-hint">Click to reveal ↗</span></span><span class="flashcard-face flashcard-back">${card[1]} ${card[2]}</span></span></button>`).join('');
document.querySelectorAll('.flashcard').forEach(card=>card.addEventListener('click',()=>card.classList.toggle('is-flipped')));
document.querySelector('#quizContainer').innerHTML=questions.map((item,index)=>`<article class="quiz-question" data-index="${index}"><div class="question-number">Question 0${index+1} · ${item.topic}</div><h3>${item.question}</h3><div class="answer-list">${item.options.map((option,optionIndex)=>`<button class="answer-option" type="button" data-option="${optionIndex}">${option}</button>`).join('')}</div></article>`).join('');
document.querySelectorAll('.quiz-question').forEach(question=>question.querySelectorAll('.answer-option').forEach(option=>option.addEventListener('click',()=>{question.querySelectorAll('.answer-option').forEach(item=>item.classList.remove('selected'));option.classList.add('selected');const answered=document.querySelectorAll('.answer-option.selected').length;document.querySelector('#quizProgressBar').style.width=`${answered/questions.length*100}%`;})));
document.querySelector('#submitQuiz').addEventListener('click',()=>{const selected=document.querySelectorAll('.answer-option.selected');if(selected.length<questions.length){document.querySelector('#resultsPanel').className='results-panel visible';document.querySelector('#resultsPanel').innerHTML='<h3>Almost there.</h3><p>Choose an answer for every question so the assessment can give you useful study guidance.</p>';document.querySelector('#resultsPanel').scrollIntoView({behavior:'smooth',block:'center'});return;}let score=0;const missed={};questions.forEach((question,index)=>{const selectedOption=Number(document.querySelector(`.quiz-question[data-index="${index}"] .selected`).dataset.option);if(selectedOption===question.answer)score++;else{if(!missed[question.topic])missed[question.topic]=[];missed[question.topic].push(question.why);}});const percentage=Math.round(score/questions.length*100);const topics=Object.entries(missed);const recommendation=topics.length?`<p>Use the recommendations below to target your next study session.</p><div class="study-list">${topics.map(([topic,notes])=>`<a href="#${topic==='Git concepts'?'start':topic==='GitHub flow'?'workflow':'vocabulary'}"><span>${topic}</span><span>${notes.length} area${notes.length>1?'s':''} to revisit →</span></a>`).join('')}</div>`:'<p>You have a strong grasp of the core ideas. Mark this module complete from the learning path and keep your momentum going.</p>';const result=document.querySelector('#resultsPanel');result.className='results-panel visible';result.innerHTML=`<span class="result-score">Assessment complete</span><h3>${score} / ${questions.length} correct · ${percentage}%</h3>${recommendation}`;result.scrollIntoView({behavior:'smooth',block:'center'});if(score>=5){const progress=JSON.parse(localStorage.getItem('gh900-progress')||'[]');if(!progress.includes('01')){progress.push('01');localStorage.setItem('gh900-progress',JSON.stringify(progress));}}});