const cards=[
  ['Repository','A project folder plus its complete history.','It can exist locally, remotely on GitHub, or in both places.'],
  ['README','The first guide a visitor sees in a repository.','Use it to explain purpose, setup, usage, and contribution steps.'],
  ['Remote','A hosted copy of a repository.','GitHub is commonly the remote shared with teammates.'],
  ['Visibility','Who can discover and access a repository.','Public is discoverable; private access is limited to people you choose.'],
  ['git init','Creates a new local Git repository.','Run it in a project folder when you want Git to begin tracking its history.'],
  ['git push','Sends local commits to a remote repository.','The first push publishes your local starting point for collaboration.']
];
const questions=[
  {topic:'Repository basics',question:'What is a repository?',options:['Only a README file','A project and its version history','A GitHub username','A pull request'],answer:1,why:'Review the repository anatomy section and the difference between a project folder and its history.'},
  {topic:'Repository basics',question:'What is the main purpose of a README?',options:['To explain the project and help people get started','To replace every commit message','To make a repository private','To delete old branches'],answer:0,why:'Revisit the README guidance: purpose, setup, usage, and the next useful step.'},
  {topic:'Repository setup',question:'Which choice controls who can discover and access a repository?',options:['The repository name','The README','Visibility','The default branch name'],answer:2,why:'Review public and private visibility choices in the create-a-repository section.'},
  {topic:'Repository setup',question:'Which command starts Git tracking in an existing local project folder?',options:['git init','git push','git status','git clone'],answer:0,why:'Revisit the first-push command strip and the role of git init.'},
  {topic:'Repository workflow',question:'What does git push do?',options:['Creates a README automatically','Sends local commits to a remote','Changes a repository name','Deletes local history'],answer:1,why:'Review how the local project moves to the shared GitHub remote.'},
  {topic:'Repository workflow',question:'What makes a repository name useful?',options:['It is as long as possible','It uses random numbers','It clearly describes the project','It matches every file name'],answer:2,why:'Revisit the naming guidance: short, recognizable, and meaningful outside your computer.'}
];

document.querySelector('#flashcardGrid').innerHTML=cards.map((card,index)=>`<button class="flashcard" type="button" aria-label="Flip flashcard ${index+1}"><span class="flashcard-inner"><span class="flashcard-face flashcard-front"><small>0${index+1} / FLASHCARD</small><strong>${card[0]}</strong><span class="flip-hint">Click to reveal ↗</span></span><span class="flashcard-face flashcard-back">${card[1]} ${card[2]}</span></span></button>`).join('');
document.querySelectorAll('.flashcard').forEach(card=>card.addEventListener('click',()=>card.classList.toggle('is-flipped')));
document.querySelector('#quizContainer').innerHTML=questions.map((item,index)=>`<article class="quiz-question" data-index="${index}"><div class="question-number">Question 0${index+1} · ${item.topic}</div><h3>${item.question}</h3><div class="answer-list">${item.options.map((option,optionIndex)=>`<button class="answer-option" type="button" data-option="${optionIndex}">${option}</button>`).join('')}</div></article>`).join('');
document.querySelectorAll('.quiz-question').forEach(question=>question.querySelectorAll('.answer-option').forEach(option=>option.addEventListener('click',()=>{question.querySelectorAll('.answer-option').forEach(item=>item.classList.remove('selected'));option.classList.add('selected');const answered=document.querySelectorAll('.answer-option.selected').length;document.querySelector('#quizProgressBar').style.width=`${answered/questions.length*100}%`;})));
document.querySelector('#submitQuiz').addEventListener('click',()=>{const selected=document.querySelectorAll('.answer-option.selected');const result=document.querySelector('#resultsPanel');if(selected.length<questions.length){result.className='results-panel visible';result.innerHTML='<h3>Almost there.</h3><p>Choose an answer for every question so the assessment can give you useful study guidance.</p>';result.scrollIntoView({behavior:'smooth',block:'center'});return;}let score=0;const missed={};questions.forEach((question,index)=>{const questionElement=document.querySelector(`.quiz-question[data-index="${index}"]`);const selectedOption=Number(questionElement.querySelector('.selected').dataset.option);const correct=questionElement.querySelector(`[data-option="${question.answer}"]`);questionElement.classList.remove('is-wrong','is-correct');questionElement.querySelectorAll('.answer-option').forEach(option=>option.classList.remove('correct-answer','wrong-answer'));correct.classList.add('correct-answer');if(selectedOption===question.answer){score++;questionElement.classList.add('is-correct');}else{questionElement.classList.add('is-wrong');questionElement.querySelector('.selected').classList.add('wrong-answer');if(!missed[question.topic])missed[question.topic]=[];missed[question.topic].push(question.why);}});const percentage=Math.round(score/questions.length*100);const topics=Object.entries(missed);const recommendation=topics.length?`<p>Use the recommendations below to target your next study session.</p><div class="study-list">${topics.map(([topic,notes])=>`<a href="#${topic==='Repository setup'?'create':topic==='Repository workflow'?'publish':'start'}"><span>${topic}</span><span>${notes.length} area${notes.length>1?'s':''} to revisit →</span></a>`).join('')}</div>`:'<p>You have a strong grasp of repository basics. Mark this module complete from the learning path and keep building.</p>';result.className='results-panel visible';result.innerHTML=`<span class="result-score">Assessment complete</span><h3>${score} / ${questions.length} correct · ${percentage}%</h3>${recommendation}`;result.scrollIntoView({behavior:'smooth',block:'center'});if(score>=5){const progress=JSON.parse(localStorage.getItem('gh900-progress')||'[]');if(!progress.includes('02')){progress.push('02');localStorage.setItem('gh900-progress',JSON.stringify(progress));}}});
